
#------------------------------------------------
- name: On-time configs
  hosts: stack_vm_1
  
  tasks:
  - name: Create a xfs filesystem on shared disk
    community.general.filesystem:
      fstype: xfs
      dev: /dev/sdc

#------------------------------------------------
- name: Install an configure the web app stack
  hosts: stack
  vars:
    x: y
  
  tasks:
  
  #---------------------
  # - name: Mount up shared disk
  #   ansible.posix.mount:
  #     src: /dev/sdc
  #     path: "{{app_dir_path}}/html/pics"
  #     fstype: xfs
  #     state: mounted

  #---------------------
  - name: Install requirements
    apt:
      name: 
       - python3
       - python3-pip
      update_cache: yes

  - name: Install python packages
    pip:
      name: flask

  #---------------------
  - name: Create app directory if it does not exist
    file:
      path: "{{app_dir_path}}"
      state: directory
      mode: 0755

  - name: Copy app data to vms
    copy:
      src: ./app/
      dest: "{{app_dir_path}}"
      owner: "{{vm_mgmt_user}}"
      group: "{{vm_mgmt_user}}"        
      mode: 0644
      
  #---------------------
  - name: Service conf file from J2 Template
    template:
      src: ./templates/webapp.service
      dest: /etc/systemd/system/webapp.service
      owner: root
      group: root
      mode: '0644'

  - name: Enable web app service
    systemd:
      name: webapp.service
      enabled: yes
      daemon_reload: yes
      state: restarted

  #---------------------